apiVersion: v1
kind: Service
metadata:
  labels:
    app: py-app
  name: py-app-svc
spec:
  selector:
    app: py-app
  ports:
  - port: 80
    targetPort: 5000
    NodePort: 32000
    name: HTTP
    protocol: TCP